# Generated by Django 5.1 on 2024-08-17 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('point', models.DecimalField(decimal_places=5, max_digits=100)),
                ('channel', models.CharField(choices=[('forrest', 'Forrest'), ('land', 'Land'), ('sea', 'Sea'), ('sky', 'Sky')], default='forrest', max_length=30)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
